name: Multi-step Demo

on:
  push:

jobs:
  demo_steps:
    runs-on: ubuntu-latest
    env:
      GITHUB_REF: ${{ github.ref }}
    steps:
      - name: Step 0 - Checkout du code
        uses: actions/checkout@v3

      - name: Step 1 - Afficher la date
        run: date

      - name: Step 2 - Afficher la branche actuelle
        run: echo "Branche actuelle : $GITHUB_REF"

      - name: Step 3 - Lister les fichiers
        run: ls -la
